### ISSUE TITLE
Minified JS?

### ISSUE THREAD

**Issue by gbasood** [AffectedArc07/SS13WebMap#1]
I was going to look into this to see if we could maintain a custom version for our codebase, but all the javascript is minified, so I can't exactly modify it easily. Would it be possible to have access to the raw script files?

**Comment by AffectedArc07** [comment]
I can generate you a custom version, just send me a full size image of your map taken with FastDMM, or link me your codebase and I will make one. Apologies for late reply.

**Comment by PJB3005** [comment]
But why not just release the source so we don't *have* to bother you?

**Comment by AffectedArc07** [comment]
Becuase I dont /have/ the source, If you read the README, this is code from Goon, and goon likes to have to source closed. They gave me permission for this, I dont even have the source.

**Comment by AffectedArc07** [comment]
@PJB3005 @gbasood if you need minified, take the code and run it through https://unminify.com/
