### ISSUE TITLE
Paradise Delta is missing the disposals outlet to space, and some possible items in the SM chamber unless im dumb and it doesnt start with them.

### ISSUE THREAD

**Issue by miniusAreas** [AffectedArc07/SS13WebMap#11]
**Issue Description: **
Arc is a weeb, and also has a semi-broken pile of code that cant find some weird and out of the way random shit every now and then.
**Affected Pages: **
Here, you nerd. https://affectedarc07.github.io/SS13WebMap/Paradise/Delta/index.html#l=217,219,1;z=2
**Steps to reproduce: **
just look at the link.

@AffectedArc07 Reminder to not make a steaming pile of shitcode. Love ya nerd no homo <3

**Comment by AffectedArc07** [comment]
![image](https://user-images.githubusercontent.com/25063394/46557581-4f18f580-c8e2-11e8-8449-3722fba3bb1a.png)
The stuff renders fine on the boxstation and metastation, making me believe its a map issue, not a renderer issue
