### ISSUE TITLE
Affected cant read titles, apparently.

### ISSUE THREAD

**Issue by miniusAreas** [AffectedArc07/SS13WebMap#12]
@AffectedArc07 I never said box / meta, literaly in the title it was said DELTA.
AAAAAAAAA

![image](https://user-images.githubusercontent.com/39163353/46622794-b78def80-caf9-11e8-9ac2-46c20251752b.png)

Updated photo.
Also sunset when?

**Comment by AffectedArc07** [comment]
You cant read either
![image](https://user-images.githubusercontent.com/25063394/46622917-ede06480-cb23-11e8-8580-6f31de4cfaca.png)
