### ISSUE TITLE
Yogstation

### ISSUE THREAD

**Issue by Jim2234** [AffectedArc07/SS13WebMap#26]
**Requested Codebase: **
Please make a yogstation map
**Original Base (TG, Bay, Other): **
TG

**Comment by AffectedArc07** [comment]
Ill do it at the weekend

**Comment by AffectedArc07** [comment]
What maps does yogs have? Can you paste the exact DMM paths please?

**Comment by Jim2234** [comment]
https://wiki.yogstation.net/wiki/Maps

**Comment by AffectedArc07** [comment]
I said exact DMM paths

**Comment by AffectedArc07** [comment]
All requests are now being handled through the discord. Please join and request the map in there so it can be kept track of
