### ISSUE TITLE
Linking coordinates is off

### ISSUE THREAD

**Issue by JohnFulpWillard** [AffectedArc07/SS13WebMap#37]
**Issue Description: ** As shown in description, linking coordinates to https://affectedarc07.github.io/SS13WebMap/TG/DeltaStation/?x=104&y=150&zoom=6 is off and doesn't properly place your view where it's supposed to be.

**Comment by LetterN** [comment]
idk if its on the js but you can just add `?x=104&y=150`

**Comment by JohnFulpWillard** [comment]
what the crap this is awesome thank you
