### ISSUE TITLE
Every single in-rotation TG map is completely empty.

### ISSUE THREAD

**Issue by TheSmallBlue** [AffectedArc07/SS13WebMap#39]
**Issue Description:**
Every map from every other server seems to load fine, but when opening up an in-rotation TG map you can only see the space background and nothing else.

Here's a video showing the problem:

https://github.com/AffectedArc07/SS13WebMap/assets/24967815/cf5ada0c-5081-47f5-91b1-e083d515b6f3

(I first open up maps from other codebases to show that they load fine, then I open up all non-working maps from TG to show that they're empty)

**Affected Pages:**
https://affectedarc07.github.io/SS13WebMap/TG/BirdShot/
https://affectedarc07.github.io/SS13WebMap/TG/DeltaStation/
https://affectedarc07.github.io/SS13WebMap/TG/IceBoxStation/
https://affectedarc07.github.io/SS13WebMap/TG/MetaStation/
https://affectedarc07.github.io/SS13WebMap/TG/NorthStar/
https://affectedarc07.github.io/SS13WebMap/TG/TramStation/

Kilo is NOT affected, it loads up fine.

**Steps to reproduce:**
* Go into https://affectedarc07.github.io/SS13WebMap/
* Scroll down to the tg section
* open up any map except kilo
* map gone

**Comment by AffectedArc07** [comment]
Fixed

**Comment by TheSmallBlue** [comment]
Christ that was fast
