### ISSUE TITLE
Oracle pubby is outdated

### ISSUE THREAD

**Issue by Cactus2388** [AffectedArc07/SS13WebMap#9]
![cryostoragepubby](https://user-images.githubusercontent.com/27895840/43395144-ad40ce26-93c2-11e8-82f5-801824e44fc1.PNG)
It was replaced with a cryostorage in: https://github.com/OracleStation/OracleStation/pull/1064 (image included)

**Comment by AffectedArc07** [comment]
Running auto update now

**Comment by AffectedArc07** [comment]
https://github.com/AffectedArc07/SS13WebMap/commit/ca9b10fdbbf254a124f074d25e4d2d1b23abf8f2
